### ISSUE TITLE
Implement going from intent recognization to generating reply

### ISSUE THREAD

**Issue by riveradelucio** [Conversational-AI-graduate-course/Open-Source-Conversational-AI-group-project#7]
**What feature is the project currently missing?**
The feature to understand specific intents and generate a reply for each intent

**How should the feature be implemented?**
The feature should be hard-coded for now.

**Are there any alternative imlpementations you have considered?**
No

**Can you offer any additional context? (Optional)**

**Comment by Riekee** [comment]
The intents i think we should program are: weather, time, or something else --> repair (e.g. can you repeat that/i don't think i can answer that question/i can help you with telling the time and the weather)
